### ISSUE TITLE
Warning: a promise was created in a handler at *  but was not returned from it

### ISSUE THREAD

**Issue by xierenyuan** [borodean/postcss-assets#79]
Trying to run postcss-assets I get the following warning:

```
Warning: a promise was created in a handler at /Users/xierenhong/rrc/fe/anne@next/node_modules/postcss/lib/container.js:110:22 but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.map (/Users/xierenhong/rrc/fe/anne@next/node_modules/bluebird/js/release/map.js:164:12)
```
my config:

```postcss-assets : { cache: true }```

**Comment by borodean** [comment]
@xierenyuan what particular config is that?
